### ISSUE TITLE
startDebugging always fails with "DialogService: refused to show dialog in tests."

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-test#207]
Trying to write an E2E test for a debugger extension (PowerShell).
`await vscode.debug.startDebugging(undefined, dotnetDebuggerConfig, session);`

Always fails with:
```
     Error: DialogService: refused to show dialog in tests.
      at v.prompt (vscode-file://vscode-app/c:/Users/jgrote/Projects/vscode-powershell/.vscode-test/vscode-win32-x64-archive-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1397:1926)
      at X.mb (vscode-file://vscode-app/c:/Users/jgrote/Projects/vscode-powershell/.vscode-test/vscode-win32-x64-archive-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1919:100497)
      at X.hb (vscode-file://vscode-app/c:/Users/jgrote/Projects/vscode-powershell/.vscode-test/vscode-win32-x64-archive-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:191      at async X.startDebugging (vscode-file://vscode-app/c:/Users/jgrote/Projects/vscode-powershell/.vscode-test/vscode-win32-x64-archive-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1919:92357)
```

I think this may be related to the debug toolbar that pops up, even if you set the setting to hidden, it still seems to trigger. Looking at other debugger extensions, none of them test this way directly it seems, but it seems reasonable that it should be possible. Does a trigger need to be added to the debug code to suppress whatever it is considering the "dialog"? I seem to have no way to identify specifically what the dialog is.

**Comment by connor4312** [comment]
This is most likely because an error occurred while starting the given debugger config. I suggest running the identical command in an interactive/non-test window and seeing the error.

**Comment by JustinGrote** [comment]
> This is most likely because an error occurred while starting the given debugger config. I suggest running the identical command in an interactive/non-test window and seeing the error.

@connor4312
That's the thing though, I have, and there's no error. I can't find any other extension repo or any test that does this successfully either, I'm pretty sure the "dialog" is the tooltip since the stacktrace is coming from startDebugging directly.

I'll dig on it some more but if you know of a repo that is doing this successfully as a test I'd like to see it.

**Comment by connor4312** [comment]
I do this in js-debug: https://github.com/microsoft/vscode-js-debug/blob/746e45e56ec928c5b8ee1fe0aa9167171381f7e1/src/test/extension/profiling.test.ts#L277-L282

**Comment by connor4312** [comment]
I made a PR in vscode to show the contents of the prompt in the error message to help in troubleshooting

**Comment by JustinGrote** [comment]
@connor4312 follow-up: You were right, I did in fact have a dialog popping up, thanks for making it easier to find it:

```
Error: DialogService: refused to show dialog in tests. Contents: DialogService: refused to show dialog in tests. Contents: Configured debug type 'PowerShell Interactive Session' is not supported.
```
