### ISSUE TITLE
Error: spawn UNKNOWN after downloading VSCode

### ISSUE THREAD

**Issue by dvirtz** [microsoft/vscode-test#234]
Getting this error in my actions Womdows workflow lately after moving to node 18:
```
100%Downloaded VS Code 1.73.1 into D:\a\vscode-parquet-viewer\vscode-parquet-viewer\.vscode-test\vscode-win32-x64-archive-1.73.1
Error: spawn UNKNOWN
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_errnoException (node:internal/errors:623:12)
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at D:\a\vscode-parquet-viewer\vscode-parquet-viewer\node_modules\@vscode\test-electron\out\runTest.js:58:24
    at new Promise (<anonymous>)
    at innerRunTests (D:\a\vscode-parquet-viewer\vscode-parquet-viewer\node_modules\@vscode\test-electron\out\runTest.js:56:12)
    at runTests (D:\a\vscode-parquet-viewer\vscode-parquet-viewer\node_modules\@vscode\test-electron\out\runTest.js:37:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
```
Tried different VSCode versions and they all fail with this error.
https://github.com/dvirtz/vscode-parquet-viewer/actions/runs/6241037762/job/16942398628

**Comment by nickmccurdy** [comment]
Can confirm the same issue on Windows. I have to ignore Windows CI failures as a workaround, but I still need to support local Windows development.
