### ISSUE TITLE
Failed to download and unzip VS Code 1.84.2 

### ISSUE THREAD

**Issue by mechatroner** [microsoft/vscode-test#244]
I am unable to run unit tests for my VSCode extension.
It looks like `win32-archive/stable` path is no longer available for version 1.84.
Perhaps the last update https://github.com/microsoft/vscode-test/commit/91c7f9c3cf746a34d766c2597f5b4cb311f932c7 could fix the issue but it hasn't been published to npm yet it seems.

Full command output: 
```
C:\wsl_share\vscode_rainbow_csv>npm run test

> rainbow-csv@3.8.0 test
> node ./test/runTest.js

starting my rainbow csv tests
extensionDevelopmentPath:C:\wsl_share\vscode_rainbow_csv, extensionTestsPath:C:\wsl_share\vscode_rainbow_csv\test\suite\index
Downloading VS Code 1.84.2 from https://update.code.visualstudio.com/1.84.2/win32-archive/stableFailed to get VS Code archive location
Error: Failed to download and unzip VS Code 1.84.2
    at download (C:\wsl_share\vscode_rainbow_csv\node_modules\@vscode\test-electron\out\download.js:193:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadAndUnzipVSCode (C:\wsl_share\vscode_rainbow_csv\node_modules\@vscode\test-electron\out\download.js:218:12)
    at async runTests (C:\wsl_share\vscode_rainbow_csv\node_modules\@vscode\test-electron\out\runTest.js:17:40)
    at async main (C:\wsl_share\vscode_rainbow_csv\test\runTest.js:18:9)
Failed to run tests
```

**Comment by mechatroner** [comment]
Are you planning to publish the update to npm soon and if not what is the workaround?
