### ISSUE TITLE
Error: @vscode/test-electron request timeout out after 15000ms

### ISSUE THREAD

**Issue by zioalex** [microsoft/vscode-test#260]
I cannot run my tests. I always get the follow error:
```
 vscode-test
Error: @vscode/test-electron request timeout out after 15000ms
    at EventTarget.<anonymous> (/workspaces/vscode-human-generated-detector-extension/node_modules/@vscode/test-electron/out/request.js:25:20)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at EventTarget.dispatchEvent (node:internal/event_target:757:26)
    at abortSignal (node:internal/abort_controller:374:10)
    at AbortController.abort (node:internal/abort_controller:396:5)
    at TimeoutController.reject (/workspaces/vscode-human-generated-detector-extension/node_modules/@vscode/test-electron/out/request.js:60:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

Here are my software version:
node  v21.6.2
npm 10.4.0
tsc 5.3.3
VSC 1.86.2

Running the tests from VSCode gives exactly the same error.

I am behind an http_proxy with a custom SSL chain. I do not think it should interfere at this stage being the test a very easy one:
```
import * as assert from 'assert';

// You can import and use all API from the 'vscode' module
// as well as import your extension to test it
import * as vscode from 'vscode';
// import * as myExtension from '../../extension';

suite('Extension Test Suite', () => {
	vscode.window.showInformationMessage('Start all tests.');

	test('Sample test', () => {
		assert.strictEqual(-1, [1, 2, 3].indexOf(5));
		assert.strictEqual(-1, [1, 2, 3].indexOf(0));
	});
});
```

**Comment by connor4312** [comment]
> I am behind an http_proxy with a custom SSL chain.

This is probably the issue. The timeout you're seeing is in the step that downloads VS Code to run tests. Please provide some more info or a reproducible setup for us. Thanks!
