### ISSUE TITLE
Error: Failed to download and unzip VS Code 1.90.2

### ISSUE THREAD

**Issue by ntananh-qas** [microsoft/vscode-test#279]
I have a extension use  `vscode-test`. When I run test using `npm run test` I got. 

```
Downloading VS Code 1.90.2 from https://update.code.visualstudio.com/1.90.2/win32-archive/stableFailed to get VS Code archive location

Error: Failed to download and unzip VS Code 1.90.2

    at download (D:\checkouts\cantata-vscode\coverage-extension\node_modules\@vscode\test-electron\out\download.js:193:15)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Object.downloadAndUnzipVSCode (D:\checkouts\cantata-vscode\coverage-extension\node_modules\@vscode\test-electron\out\download.js:218:12)

    at async Module.runTests (D:\checkouts\cantata-vscode\coverage-extension\node_modules\@vscode\test-electron\out\runTest.js:17:40)

    at async runPreparedConfigs (file:///D:/checkouts/cantata-vscode/coverage-extension/node_modules/@vscode/test-cli/out/bin.mjs:117:31)

    at async main (file:///D:/checkouts/cantata-vscode/coverage-extension/node_modules/@vscode/test-cli/out/bin.mjs:33:20)
   
   ```
   
   My VSCode installattion:
   ```
Version: 1.90.2 (system setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045   
```

The package.json  of my extension

![image](https://github.com/microsoft/vscode-test/assets/172796930/d2f6c3b6-d385-403e-8b2a-182a2e08d203)

I already found a related issue #244  but I still don't know how to fix it. Does anyone have any information about it ?

**Comment by ntananh-qas** [comment]
Close, I use an outdated version of `@vscode/test-electron`. Update to v2.4.0 worked for me. 

Thanks
